Update the run script with the generator
Use generator-canonical-webteam@0.1.6 to update to latest version of the
run script.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,44 +1,44 @@
 #! /usr/bin/env bash
 
+# CAUTION:
+# This file should usually not be edited directly.
+#
+# This file was generated by the "canonical-webteam" Yeoman generator
+# https://npmjs.org/package/generator-canonical-webteam
+#
+# Update it to the latest version with:
+#
+# $ sudo npm install -g yo generator-canonical-webteam
+# $ yo canonical-webteam:run-django
+
 set -euo pipefail
 
 # Define the versions of the two docker images
 django_image="canonicalwebteam/django:v1.2.2"
-yarn_image="canonicalwebteam/yarn:v0.2.0"
+yarn_image="canonicalwebteam/yarn:v0.3.0"
 
-# Usage instructions
 USAGE="Usage
 ===
 
   $ ./run \\
-    [-p|--port NUM]          # Specify local port for server \\
     [-m|--node-module PATH]  # A path to a local node module to use instead of the installed dependencies \\
-    [-d|--detach]            # Detach container to the backgorund \\
     [--no-debug]             # Turn off Django's DEBUG setting \\
     [COMMAND]                # Optionally provide a command to run
 
-If no COMMAND is provided, \`start\` will be run.
+If no COMMAND is provided, \`serve\` will be run.
 
 Commands
 ---
 
-- start [-w|--watch]: Run the development server (optionally watching for Sass changes) \\
+- serve [-p|--port PORT] [-w|--watch] [-d|--detach]: Run Run the development server (optionally running \`watch\` in the background)
 - watch: Run \`yarn run watch\`
 - build: Run \`yarn run build\`
-- test: Run \`yarn run test\` and \`./manage.py test\`
+- test: Run \`yarn run test\`
+- stop: Stop any running containers
 - yarn <args>: Run yarn
 - django <args>: Run ./manage.py <args>
 - clean: Remove all images and containers, any installed dependencies and the .docker-project file
 - clean-cache: Empty cache files, which are saved between projects (eg, yarn)
-
-Persistent options
----
-
-The options can also be defined in a local \`.env\` file, e.g.:
-
-  # These are the default settings
-  PORT=8000                 # Run the server on local port 8000
-  DJANGO_DEBUG=true         # Enable Django's DEBUG mode
 "
 
 ##
@@ -65,132 +65,125 @@ fi
 
 # Generate the project name
 if [[ -f ".docker-project" ]]; then
-  project=$(cat .docker-project)
+    project=$(cat .docker-project)
 else
-  directory=$(basename `pwd`)
-  hash=$((pwd | md5sum 2> /dev/null || md5 -q -s `pwd`) | cut -c1-8)
-  project=canonical-webteam-${directory}-${hash}
-  echo $project > .docker-project
+    directory=$(basename `pwd`)
+    hash=$((pwd | md5sum 2> /dev/null || md5 -q -s `pwd`) | cut -c1-8)
+    project=canonical-webteam-${directory}-${hash}
+    echo $project > .docker-project
 fi
 
-# Defaults
-DETACH=''
+# Settings
+module_volumes=()
+yarn_cache_volume="${CANONICAL_WEBTEAM_YARN_CACHE_VOLUME:-canonical-webteam-yarn-cache}"
+[ -t 1 ] && tty="--tty --interactive" || tty=""           # Do we have a terminal?
+[ -f .env ] && env_file="--env-file .env" || env_file=""  # Do we have an env file?
+pip_dependencies_volume="${project}-pip-dependencies"
+
+
+# Defaults environment settings
 PORT=8000
 DJANGO_DEBUG=true
-
-# Read current environment variables
+# Import environment settings
 if [ -f .env ]; then
     export $(cat .env | grep -v ^\# | xargs)
 fi
 
-# Optional arguments
-# ==
-#  --port {port} - The local port to run the web service on
-#  --node-module {path} - Path to a local version of a node module
-#  --no-debug - Turn off Django DEBUG mode
-#  --help - Show usage instructions
 invalid() {
-    echo "Command not recognised."
+    message=${1}
+    echo "Error: ${message}"
     echo ""
     echo "$USAGE"
     exit 1
 }
 
-module_volumes=()
-
+# Read optional arguments
 while [[ -n "${1:-}" ]] && [[ "${1:0:1}" == "-" ]]; do
     key="$1"
 
     case $key in
-        -d|--detach) DETACH='--detach' ;;
-        -p|--port)
-            if [ -z "${2:-}" ]; then invalid; fi
-            PORT="$2"
-            shift
-        ;;
+
+        --no-debug) DJANGO_DEBUG=false ;;
+
         -m|--node-module)
-            if [ -z "${2:-}" ]; then invalid; fi
+            if [ -z "${2:-}" ]; then invalid "Missing module name. Usage: --node-module <path-to-module>."; fi
             module_volumes+=("--volume" "${2}":"`pwd`/node_modules/$(basename ${2})")
             shift
         ;;
-        --no-debug) DJANGO_DEBUG=false ;;
         -h|--help) echo "$USAGE"; exit ;;
-        *) invalid ;;
+        *) invalid "Option '${key}' not recognised." ;;
     esac
     shift
 done
 
-rm_docker_container() {
-  container_name="${1}"
-  # Kill any previously running containers
-  if docker ps --all | grep -q ${container_name}; then
-    echo "Removing container:"
-    docker rm --force ${container_name} || true
-  fi
+kill_container () {
+    container_name="${1}"
+
+    # Kill any previous containers
+    previous_id=$(docker ps --all --quiet --filter "name=^/${container_name}$")
+    if [ -n "${previous_id}" ]; then
+        docker rm --force ${previous_id} > /dev/null;
+    fi
 }
 
-docker_run() {
-  # The standard set of "docker run" arguments
+run_as_user () {
+    # Run a container as the current user and in the current directory context
 
-  [ -t 1 ] && tty="--tty --interactive" || tty=""  # Do we have a terminal?
-  [ -f .env ] && env_file="--env-file .env" || env_file=""  # Do we have an env file?
+    # Get options
+    container_name=${1}; shift  # Get container_name as first argument
 
-  docker run  \
-    --user $(id -u):$(id -g)  `# Use the current user inside container`  \
-    ${env_file}               `# Pass environment variables into the container, if file exists`  \
-    --rm                      `# Tidy up by deleting the container when it stops`  \
-    --volume `pwd`:`pwd`      `# Mirror current directory inside container`  \
-    --workdir `pwd`           `# Set current directory to the image's work directory`  \
-    ${tty}                    `# Attach a pseudo-terminal, if relevant`  \
-    $@                        `# Extra arguments`
+    # Kill existing containers
+    kill_container "${container_name}"
+
+    # Start the new container
+    docker run  \
+        --name ${container_name}  `# Name the container` \
+        --rm                      `# Remove the container once it's finished`  \
+        --user $(id -u):$(id -g)  `# Use the current user inside container`  \
+        ${env_file}               `# Pass environment variables into the container, if file exists`  \
+        --volume `pwd`:`pwd`      `# Mirror current directory inside container`  \
+        --workdir `pwd`           `# Set current directory to the image's work directory`  \
+        ${tty}                    `# Attach a pseudo-terminal, if relevant`  \
+        $@                        `# Extra arguments`
 }
 
-docker_django () {
-  container_name="${project}-django"
-  rm_docker_container "${container_name}"
 
-  # Run Django using the docker image
-  docker_run  \
-    --name ${container_name} \
-    --volume ${project}-dependencies:/usr/local/lib/python2.7/site-packages  `# Store dependencies in a docker volume`  \
-    --publish ${PORT}:${PORT}  `# Export the server port`  \
-    --env PORT=${PORT}  `# Set the port correctly`  \
-    ${DETACH} `# Detach from session if flag is set`  \
-    $django_image $@  `# Run the django image`
-}
 
-docker_yarn () {
-  container_name="${project}-yarn"
-  rm_docker_container "${container_name}"
+yarn_run () {
+    # Standard options for running yarn
+    container_name="${1}"
+    command="${2:-}"
+    extra_options="${3:-}"
 
-  # Run "yarn" from the "node" image
-  docker_run  \
-    --name ${container_name} \
-    --volume ${CANONICAL_WEBTEAM_YARN_CACHE_VOLUME:-canonical-webteam-yarn-cache}:/home/shared/.cache/yarn/  `# Bind yarn cache to volume` \
-    ${module_volumes[@]+"${module_volumes[@]}"}  `# Add any override modules as volumes`  \
-    $yarn_image $@              `# Use the image for node version 7`
+    # Run "yarn" from the "node" image
+    run_as_user "${container_name}"  \
+        --volume ${yarn_cache_volume}:/home/shared/.cache/yarn/  `# Bind yarn cache to volume` \
+        ${module_volumes[@]+"${module_volumes[@]}"}  `# Add any override modules as volumes`  \
+        ${extra_options}                             `# Extra options`  \
+        ${yarn_image} ${command}                     `# Run command in yarn image`
 }
 
 yarn_install () {
-  container_name="${project}-yarn-install"
-  rm_docker_container "${container_name}"
-
-  # Install yarn dependencies, without module overrides
-  docker_run \
-    --name ${container_name} \
-    --volume ${CANONICAL_WEBTEAM_YARN_CACHE_VOLUME:-canonical-webteam-yarn-cache}:/home/shared/.cache/yarn/  `# Bind yarn cache to volume` \
-    ${yarn_image} install
+    # Install yarn dependencies, without module overrides
+    run_as_user "${project}-install" \
+        --volume ${yarn_cache_volume}:/home/shared/.cache/yarn/  `# Bind yarn cache to volume` \
+        ${yarn_image} install  `# Install yarn dependencies`
 }
 
-clean_cache () {
-  # Clean yarn cache volume
-  if docker volume ls | grep -q canonical-webteam-yarn-cache; then
-    echo "Deleting cache volume:"
-    docker volume rm --force canonical-webteam-yarn-cache
-  else
-    echo "No cache volume found"
-  fi
+django_run () {
+    container_name="${1}"
+    command="${2:-}"
+    extra_options="${3:-}"
+
+    # Run Django using the docker image
+    run_as_user ${container_name} \
+        --volume ${pip_dependencies_volume}:/usr/local/lib/python2.7/site-packages  `# Store dependencies in a docker volume`  \
+        --env PORT=${PORT}                        `# Set the port correctly`  \
+        --env DJANGO_DEBUG=${DJANGO_DEBUG}        `# Set django debug mode`  \
+        ${extra_options}                          `# Any extra docker options`  \
+        ${django_image} ${command}                `# Run command in the Django image`
 }
+
 
 # Find current run command
 run_command=${1:-}
@@ -198,49 +191,86 @@ if [[ -n "${run_command}" ]]; then shift; fi
 
 # Do the real business
 case $run_command in
-  ""|"start")
-    yarn_install
-    docker_yarn run build
+    ""|"serve")
+        yarn_install
 
-    # Run watch command in the background
-    if [[ ${1:-} == "--watch" ]] || [[ ${1:-} == "-w" ]]; then
-      container_name="${project}-yarn-watch"
-      rm_docker_container "${container_name}"
-      docker_run  \
-        --name ${container_name}  `# Name the unit so it can be killed` \
-        --detach                  `# Run in the background` \
-        $yarn_image run watch     `# Use the image for node version 7`
-      trap "rm_docker_container '${container_name}'" EXIT
-    fi
+        # Read optional arguments
+        detach=""
+        run_watcher=false
+        while [[ -n "${1:-}" ]] && [[ "${1:0:1}" == "-" ]]; do
+            key="$1"
 
-    docker_django
-  ;;
-  "watch")
-    yarn_install
-    docker_yarn run build
-    docker_yarn run watch
-  ;;
-  "build")
-    yarn_install
-    docker_yarn run build
-  ;;
-  "test")
-    yarn_install
-    docker_yarn run test
-    docker_django test
-  ;;
-  "clean")
-    project_containers="$(docker ps -aq --filter name=${project})"
-    if [ -n "${project_containers}" ]; then
-      docker rm --force $project_containers
-    fi
-    rm -rf node_modules .docker-project
-    docker volume rm --force ${project}-dependencies
-  ;;
-  "clean-cache")
-    clean_cache $@
-  ;;
-  "django") docker_django $@ ;;
-  "yarn") docker_yarn $@ ;;
-  *) invalid ;;
+            case $key in
+                -d|--detach) detach="--detach" ;;
+                -p|--port)
+                    if [ -z "${2:-}" ]; then invalid "Missing port number. Usage: --port XXXX"; fi
+                    PORT=${2}
+                    shift
+                ;;
+                -w|--watch) run_watcher=true ;;
+                *) invalid "Option '${key}' not recognised." ;;
+            esac
+            shift
+        done
+
+        yarn_run "${project}-build" "run build"
+
+        # Run watch command in the background
+        if ${run_watcher}; then
+            if [ -z "${detach}" ];  then trap "kill_container ${project}-watch" EXIT; fi
+            yarn_run "${project}-watch" "run watch" "--detach"  # Run watch in the background
+        fi
+
+        
+
+        # Run the serve container, publishing the port, and detaching if required
+        django_run "${project}-serve" "" "--env PORT=${PORT} --publish ${PORT}:${PORT} ${detach}"
+        
+    ;;
+    "stop")
+        echo "Stopping all running containers for ${project}"
+        running_containers="$(docker ps --quiet --filter name=${project})"
+        docker kill ${running_containers}
+    ;;
+    "watch")
+        
+        yarn_install
+        yarn_run "${project}-build" "run build"
+        yarn_run "${project}-watch" "run watch"
+    ;;
+    "build")
+        yarn_install
+        yarn_run "${project}-build" "run build"
+        
+    ;;
+    "test")
+        yarn_install
+        yarn_run "${project}-yarn-test" "run test"
+        django_run "${project}-django-test" "test"
+    ;;
+    "clean")
+        echo "Running 'clean' yarn script"
+        yarn_run "${project}-clean" "run clean" || true  # Run the clean script
+
+        echo "Removing all containers, volumes and networks for project: ${project}"
+        project_containers="$(docker ps --all --quiet --filter name=${project})"
+        project_volumes="$(docker volume ls --quiet --filter name=${project})"
+        project_networks="$(docker network ls --quiet --filter name=${project})"
+        if [ -n "${project_containers}" ]; then docker rm --force ${project_containers}; fi
+        if [ -n "${project_volumes}" ]; then docker volume rm --force ${project_volumes}; fi
+        if [ -n "${project_networks}" ]; then docker network rm ${project_networks}; fi
+
+        echo "Removing .docker-project file"
+        rm -rf .docker-project  # Remove the project file
+    ;;
+    "clean-cache")
+        # Clean yarn cache volume
+        echo "Removing cache volume ${yarn_cache_volume}"
+        containers_using_volume=$(docker ps --quiet --all --filter "volume=canonical-webteam-yarn-cache")
+        if [ -n "${containers_using_volume}" ]; then docker rm --force ${containers_using_volume}; fi
+        docker volume rm --force ${yarn_cache_volume}
+    ;;
+    "django") django_run "${project}-django-$(date +'%s')" "${@}" "--rm" ;;
+    "yarn") yarn_run "${project}-yarn-$(date +'%s')" "${@}" ;;
+    *) invalid "Command '${run_command}' not recognised." ;;
 esac
