ci(performance-checks): refactor failure tracking

diff --git a/.github/workflows/performance-check.yaml b/.github/workflows/performance-check.yaml
--- a/.github/workflows/performance-check.yaml
+++ b/.github/workflows/performance-check.yaml
@@ -1,15 +1,13 @@
 name: Performance checks on ubuntu.com
 
-# on:
-#   on: [push]
-#     schedule:	
-#       - cron: "20 7 * * 1"	
-#     workflow_dispatch:
-on: [push]
+on:
+  [push]
+  # schedule:
+  #   - cron: "20 7 * * 1"
+  # workflow_dispatch:
 
 env:
-  THRESHOLD: 70
-  FAILURE_COUNT: 0
+  THRESHOLD: 50
 
 jobs:
   perf-checks:
@@ -18,6 +16,7 @@ jobs:
 
     steps:
       - name: Running performance checks on the homepage
+        id: homepage
         continue-on-error: true
         uses: jakepartusch/psi-action@v1.3
         with:
@@ -25,12 +24,8 @@ jobs:
           url: "https://ubuntu.com"
           threshold: $THRESHOLD
           strategy: desktop
-        id: homepage
-      - name: Track homepage failure
-        if: steps.homepage.outcome == 'failure'
-        run: echo "FAILURE_COUNT=$((FAILURE_COUNT + 1))" >> $GITHUB_ENV
-
       - name: Running performance checks on the desktop overview page
+        id: desktop
         continue-on-error: true
         uses: jakepartusch/psi-action@v1.3
         with:
@@ -38,12 +33,8 @@ jobs:
           url: "https://ubuntu.com/desktop"
           threshold: $THRESHOLD
           strategy: desktop
-        id: desktop
-      - name: Track desktop failure
-        if: steps.desktop.outcome == 'failure'
-        run: echo "FAILURE_COUNT=$((FAILURE_COUNT + 1))" >> $GITHUB_ENV
-
       - name: Running performance checks on the download overview page
+        id: download
         continue-on-error: true
         uses: jakepartusch/psi-action@v1.3
         with:
@@ -51,12 +42,8 @@ jobs:
           url: "https://ubuntu.com/download"
           threshold: $THRESHOLD
           strategy: desktop
-        id: download
-      - name: Track download failure
-        if: steps.download.outcome == 'failure'
-        run: echo "FAILURE_COUNT=$((FAILURE_COUNT + 1))" >> $GITHUB_ENV
-
       - name: Running performance checks on the blog
+        id: blog
         continue-on-error: true
         uses: jakepartusch/psi-action@v1.3
         with:
@@ -64,12 +51,8 @@ jobs:
           url: "https://ubuntu.com/blog"
           threshold: $THRESHOLD
           strategy: desktop
-        id: blog
-      - name: Track blog failure
-        if: steps.blog.outcome == 'failure'
-        run: echo "FAILURE_COUNT=$((FAILURE_COUNT + 1))" >> $GITHUB_ENV
-
       - name: Running performance checks on the openstack overview
+        id: openstack
         continue-on-error: true
         uses: jakepartusch/psi-action@v1.3
         with:
@@ -77,12 +60,8 @@ jobs:
           url: "https://ubuntu.com/openstack"
           threshold: $THRESHOLD
           strategy: desktop
-        id: openstack
-      - name: Track openstack failure
-        if: steps.openstack.outcome == 'failure'
-        run: echo "FAILURE_COUNT=$((FAILURE_COUNT + 1))" >> $GITHUB_ENV
-
       - name: Running performance checks on the kubernetes overview
+        id: kubernetes
         continue-on-error: true
         uses: jakepartusch/psi-action@v1.3
         with:
@@ -90,12 +69,8 @@ jobs:
           url: "https://ubuntu.com/kubernetes"
           threshold: $THRESHOLD
           strategy: desktop
-        id: kubernetes
-      - name: Track kubernetes failure
-        if: steps.kubernetes.outcome == 'failure'
-        run: echo "FAILURE_COUNT=$((FAILURE_COUNT + 1))" >> $GITHUB_ENV
-
       - name: Running performance checks on the managed overview
+        id: managed
         continue-on-error: true
         uses: jakepartusch/psi-action@v1.3
         with:
@@ -103,12 +78,8 @@ jobs:
           url: "https://ubuntu.com/managed"
           threshold: $THRESHOLD
           strategy: desktop
-        id: managed
-      - name: Track managed failure
-        if: steps.managed.outcome == 'failure'
-        run: echo "FAILURE_COUNT=$((FAILURE_COUNT + 1))" >> $GITHUB_ENV
-
       - name: Running performance checks on the ai overview
+        id: ai
         continue-on-error: true
         uses: jakepartusch/psi-action@v1.3
         with:
@@ -116,12 +87,8 @@ jobs:
           url: "https://ubuntu.com/ai"
           threshold: $THRESHOLD
           strategy: desktop
-        id: ai
-      - name: Track ai failure
-        if: steps.ai.outcome == 'failure'
-        run: echo "FAILURE_COUNT=$((FAILURE_COUNT + 1))" >> $GITHUB_ENV
-
       - name: Running performance checks on the robotics overview
+        id: robotics
         continue-on-error: true
         uses: jakepartusch/psi-action@v1.3
         with:
@@ -129,12 +96,8 @@ jobs:
           url: "https://ubuntu.com/robotics"
           threshold: $THRESHOLD
           strategy: desktop
-        id: robotics
-      - name: Track robotics failure
-        if: steps.robotics.outcome == 'failure'
-        run: echo "FAILURE_COUNT=$((FAILURE_COUNT + 1))" >> $GITHUB_ENV
-
       - name: Running performance checks on the core overview
+        id: core
         continue-on-error: true
         uses: jakepartusch/psi-action@v1.3
         with:
@@ -142,12 +105,8 @@ jobs:
           url: "https://ubuntu.com/core"
           threshold: $THRESHOLD
           strategy: desktop
-        id: core
-      - name: Track core failure
-        if: steps.core.outcome == 'failure'
-        run: echo "FAILURE_COUNT=$((FAILURE_COUNT + 1))" >> $GITHUB_ENV
-
       - name: Running performance checks on the cloud overview
+        id: cloud
         continue-on-error: true
         uses: jakepartusch/psi-action@v1.3
         with:
@@ -155,12 +114,8 @@ jobs:
           url: "https://ubuntu.com/cloud"
           threshold: $THRESHOLD
           strategy: desktop
-        id: cloud
-      - name: Track cloud failure
-        if: steps.cloud.outcome == 'failure'
-        run: echo "FAILURE_COUNT=$((FAILURE_COUNT + 1))" >> $GITHUB_ENV
-
       - name: Running performance checks on the tutorials overview
+        id: tutorials
         continue-on-error: true
         uses: jakepartusch/psi-action@v1.3
         with:
@@ -168,12 +123,8 @@ jobs:
           url: "https://ubuntu.com/tutorials"
           threshold: $THRESHOLD
           strategy: desktop
-        id: tutorials
-      - name: Track tutorials failure
-        if: steps.tutorials.outcome == 'failure'
-        run: echo "FAILURE_COUNT=$((FAILURE_COUNT + 1))" >> $GITHUB_ENV
-
       - name: Running performance checks on a tutorial
+        id: tutorial-example
         continue-on-error: true
         uses: jakepartusch/psi-action@v1.3
         with:
@@ -181,17 +132,59 @@ jobs:
           url: "https://ubuntu.com/tutorials/how-to-upgrade-ubuntu-lts-to-ubuntu-pro-on-aws-using-aws-license-manager#1-overview"
           threshold: $THRESHOLD
           strategy: desktop
-        id: tutorial
-      - name: Track tutorial failure
-        if: steps.tutorial.outcome == 'failure'
-        run: echo "FAILURE_COUNT=$((FAILURE_COUNT + 1))" >> $GITHUB_ENV
 
-      - name: Check for any failures
-        if: env.FAILURE_COUNT > 0
+      - name: Check overall results
         run: |
-          echo "Performance checks failed for $FAILURE_COUNT page(s)."
-          exit 1
+          failed_checks=""
+          
+          if [ "${{ steps.homepage.outcome }}" = "failure" ]; then
+            failed_checks="$failed_checks homepage"
+          fi
+          if [ "${{ steps.desktop.outcome }}" = "failure" ]; then
+            failed_checks="$failed_checks desktop"
+          fi
+          if [ "${{ steps.download.outcome }}" = "failure" ]; then
+            failed_checks="$failed_checks download"
+          fi
+          if [ "${{ steps.blog.outcome }}" = "failure" ]; then
+            failed_checks="$failed_checks blog"
+          fi
+          if [ "${{ steps.openstack.outcome }}" = "failure" ]; then
+            failed_checks="$failed_checks openstack"
+          fi
+          if [ "${{ steps.kubernetes.outcome }}" = "failure" ]; then
+            failed_checks="$failed_checks kubernetes"
+          fi
+          if [ "${{ steps.managed.outcome }}" = "failure" ]; then
+            failed_checks="$failed_checks managed"
+          fi
+          if [ "${{ steps.ai.outcome }}" = "failure" ]; then
+            failed_checks="$failed_checks ai"
+          fi
+          if [ "${{ steps.robotics.outcome }}" = "failure" ]; then
+            failed_checks="$failed_checks robotics"
+          fi
+          if [ "${{ steps.core.outcome }}" = "failure" ]; then
+            failed_checks="$failed_checks core"
+          fi
+          if [ "${{ steps.cloud.outcome }}" = "failure" ]; then
+            failed_checks="$failed_checks cloud"
+          fi
+          if [ "${{ steps.tutorials.outcome }}" = "failure" ]; then
+            failed_checks="$failed_checks tutorials"
+          fi
+          if [ "${{ steps.tutorial-example.outcome }}" = "failure" ]; then
+            failed_checks="$failed_checks tutorial-example"
+          fi
+          
+          if [ -n "$failed_checks" ]; then
+            echo "Performance checks failed for:$failed_checks"
+            echo "FAILED_CHECKS=$failed_checks" >> $GITHUB_ENV
+            exit 1
+          else
+            echo "All performance checks passed!"
+          fi
 
-      # - name: Send message on failure
-      #   if: env.FAILURE_COUNT > 0
-      #   run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=web-design
+      - name: Send message on failure
+        if: failure()
+        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" -F "failed_checks=${FAILED_CHECKS}" ${{ secrets.BOT_URL }}?room=web-design
